[package]
name = "sfox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
futures = "0.3.28"
futures-util = "0.3.28"

reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.171"
serde_derive = "1.0.171"
serde_json = "1.0.103"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }

[dev-dependencies]
mockito = "1.1.0"
tokio-test = "0.4.2"
